const languages = ['html', 'css', 'javascript', 'react', 'node', 'postgres'];
console.log('languages: ' + languages);
const firstElement = languages[0];
console.log('The first element is ' + firstElement);
const thirdElement = languages[2];
console.log('The third element is ' + thirdElement);
const arrayLength = languages.length;
console.log('The length of the array is ' + arrayLength);
const lastElement = languages[5];
console.log('The last element is ' + lastElement);
