let number1 = 8;
let number2 = 4;
const product = number1 * number2;
console.log('value of product: ' + product);
console.log(typeof product);
let charge = 6;
let payment = 4;
const amountRemaining = charge - payment;
console.log('Remaining balance: ' + amountRemaining);
console.log(typeof amountRemaining);
let test = 98;
let assignments = 85;
let final = 90;
const grade = (98 + 85 + 90) / 3;
console.log('Your grade is: ' + grade);
console.log(typeof grade);
let firstName = 'CharLee-Kyle ';
let lastName = 'Gaff';
const fullName = firstName + lastName;
console.log('Full Name:' + fullName);
console.log(typeof fullName);
let pH = 10;
const isAcidic = pH < 7;
console.log('Is Acidic?: ' + isAcidic);
console.log(typeof isAcidic);
let numberOfSoldiers = 275;
const isSparta = 300 === 275;
console.log('Army size 300?: ' + isSparta);
console.log(typeof isSparta);
let nickname = fullName + 'is the Goat';
console.log('Nickname is: ' + nickname);
console.log(typeof nickname);
